---
latitude: 40.80921
longitude: -73.95184
map_zoom: 12
name: Aloft Harlem
email: sgontu@traveltripper.com
phone_number: 001-111-1111
address:
  street1: 2296 Frederick Douglass Boulevard
  street2: ''
  state: New York
  city: New York
  country: United States
  zip_code: '10027'
_hotel_id: ALO529
_portal_id: required-but-empty
_root_path: https://rt3api-prd.ttaws.com
